### ISSUE TITLE
888 komplett daneben

### ISSUE THREAD

**Issue by viisauksena** [FreiFunkMuenster/packages-ffms#1]
```
#!/bin/sh

echo "#!/bin/bash" > /etc/rc.button/rfkill
echo "echo "WiFi On/Off pressed. Doing nothing." > /dev/console" >> /etc/rc.button/rfkill
echo "return 0" >> /etc/rc.button/rfkill
```

ihr überschreibt da die Datei ... das ist soweit ok, wenn auch gaga denn vermutlich würde es reichen die 
`rm /etc/rc.button/rfkill` zu benutzen, statt der ganzen echo ...
und diese haben auch massiv Fehler !
1. bin/bash gibt es auf den routern nicht
2. müsste das auch wieder ausführbar gemacht werden (chmod a+x /etc/rc.bu...)
3.  echo" echo" .. double quote hölle, die müssten mindestens escaped werden

**Comment by rubo77** [comment]
/bin/sh würde gehen?

Und bei dem Echo würde ich einfach quotes benutzen: '

```
echo 'echo "WiFi On/Off pressed. Doing nothing." > /dev/console' >> /etc/rc.button/rfkill
```

Ist das korrekt einfach dev/console zu beschreiben?

Gibts da nicht eine sauberere Lösung als überschreiben?

**Comment by HellMar** [comment]
Danke für die Hinweise aber Ist wie schon gesagt noch nicht fertig...
Hatte das nur schon mal Niedergeschrieben...
Ausserdem finde ich persönlich es sinnvoller eine vom System vorhandene Datei nicht einfach zu löschen... Dann doch lieber mit anderem, wenn auch sinnfreiem Inhalt füllen.

**Comment by rubo77** [comment]
Welcher Prozess ruft das Script überhaupt auf?

**Comment by viisauksena** [comment]
das gluon magie ... :) ... siehe mal dies hier an
https://github.com/freifunk-gluon/gluon/blob/master/docs/dev/upgrade.rst

**Comment by viisauksena** [comment]
https://github.com/FreiFunkMuenster/packages-ffms/pull/2 
was immer noch keine garantie ist, das das auch funktioniert, nur ist das eben ein saubereres skript

**Comment by HellMar** [comment]
Cool danke. Werd mal eine FW bauen und Testen.

**Comment by viisauksena** [comment]
feedback obs geht wär noch ganz gut .. wenn du das testest - für Menschen die das hier finden
