### ISSUE TITLE
Obsolete Pakete in v2018.1.x

### ISSUE THREAD

**Issue by jotzt** [FreiFunkMuenster/packages-ffms#8]
~~Die Pakete `gluon-ssid-changer` und `gluon-rfkill-disable` sind in v2018.1 integriert und können via `GLUON_FEATURES` aktiviert werden.~~
Das Paket `gluon-config-mode-show-mac` ist überflüssig, stattdessen kann in den `i18n`-Dateien anstatt der Variable `macaddr` der Code `string.gsub(sysconfig.primary_mac, ':', '')` verwendet werden.

**Comment by MPW1412** [comment]
Hättest du Lust das mal alles zusammen zu bauen und deine Konfiguration (für eine Domäne) irgendwo hochzuladen. Ich hab einfach derzeit viel zu tun.

**Comment by RobWei** [comment]
Ich habe bereits einen kompletten Satz aktueller site.conf´s mit @jotzt und ein paar weiteren Änderungen generiert.

https://github.com/RobWei/site-ffms/tree/Domäne-01-v2018.1.x
https://github.com/RobWei/site-ffms/tree/Domäne-02-v2018.1.x
usw.

**Comment by HellMar** [comment]
Ich will ja kein Spielverderber sein aber das hier:
https://github.com/RobWei/site-ffms/blob/Domäne-01-v2018.1.x/site.mk#L22-L23 
lädt die beiden Module aus unserem Repo mit in die Firmware. Das einzige was sich geändert hat ist das ein "gluon-" automatisch vorn an das Paket angehängt wird. 

Das `gluon-config-mode-show-mac` ist tatsächlich überflüssig dann...

**Comment by RobWei** [comment]
Jo.. Im prinzip müssen jetzt nur noch das RFKill, ssid-changer und show-mac
aus dem package repo entfernt werden oder?

**Comment by HellMar** [comment]
Ähm ne eben nicht... wenn du es da entfernst wird der build Fehlschlagen weil es im Gluon kein Paket gibt das gluon-ssid-changer und gluon-rfkill-disable heißt.

**Comment by RobWei** [comment]
Also sind die Pakete doch nicht integriert?

**Comment by HellMar** [comment]
Das versuche ich euch zu erklären ja... :grinning:

**Comment by jotzt** [comment]
Okay, ganz habe ich das noch nicht gescheckt. Ich war davon ausgegangen, dass GLUON-FEATURES das impliziert. Erklärt auch die Fehler beim Build gestern. 

Ich nehme alles zurück und behaupte das Gegenteil.
